### ISSUE TITLE
URLs in Zimbra Chrome Fix need to be updated

### ISSUE THREAD

**Issue by rsaeks** [Zimbra-Community/zimbra-patches#1]
There are updates to the URLs needed in the fix script:

wget --no-check-certificate https://raw.githubusercontent.com/jorgedlcruz/Zimbra/master/Zimbra%20Google%20Chrome%2045%20Fix/_base2skin.css https://raw.githubusercontent.com/jorgedlcruz/Zimbra/master/Zimbra%20Google%20Chrome%2045%20Fix/_base3skin.css

that need to be updated with the new repo URL.

**Comment by ghost** [comment]
You should no longer need this patch, but it is fixed now.

https://github.com/Zimbra-Community/zimbra-patches/commit/b4efbd4d23d2a847354a3bd55f01cfa4130bf891
