### ISSUE TITLE
cal patch missing all day events

### ISSUE THREAD

**Issue by MACscr** [Zimbra-Community/zimbra-patches#2]
Your patch removes the all day events that are normally at the top of the calendars. =(

**Comment by ghost** [comment]
Hello MACscr,

Thanks for reporting, please remember that I am not working at Zimbra and I am patching this voluntary.

I fixed the all-day appointment issue, you can install the new version by following the instruction in readme:
https://github.com/Zimbra-Community/zimbra-patches#calendar-day-view-in-87-is-broken-if-too-many-calendars-are-in-the-users-account-httpsbugzillazimbracomshow_bugcgiid106285
